name = "Pathways"
uuid = "19ca04dd-1ee6-4c1f-95e1-86f6eb7fb173"
authors = ["Douglas G. Moore <doug@dglmoore.com>"]
version = "0.1.0"

[deps]

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Printf", "Statistics", "Test"]
